### PR TITLE
Sayed mosavi

### PR DESCRIPTION
**Pull request by Mosavi1988**
Try your best to achieve what you need

### CODE REVIEW

**Comment by adamrochwick** [comment]
Oh boy conflict!

**Review by isharoyan — APPROVED** [review]

**Review by JosueValladares — COMMENTED** [review]
This looks great!!! way to go for the 6 figures salary

**Review by mhnexpress — COMMENTED** [review]
good job

**Review by isharoyan — APPROVED** [review]

**Review by mhnexpress — COMMENTED** [review]
nice

**Review by mhnexpress — COMMENTED** [review]
good luck

**Review by adamrochwick — COMMENTED** [review]
Nice.

**Comment by Pahan4k** [comment]
Good job

**Review by isharoyan — APPROVED** [review]

**Comment by isharoyan** [comment]
all good

**Review by isharoyan — APPROVED** [review]

**Pull request merged**
